In [1]:
import numpy as np
import pandas as pd 

##### Pandas, NumPy'nin sagladigi hiz ve verimliligin uzerine insa edilmis, daha ust duzey ve tablo benzeri veriler için daha kullanisli bir kutuphanedir.__Yani pandas'in temel yapi taslari Numpy arraylari'dir.__

# Series

#### tek boyutlu, etiketli bir veri yapisidir. Sanki bir Excel sutunu gibi dusunebilirsin.

In [2]:
notlar={"ali":75, "mustafa":85, "aybuke":80} #elimizde boyle bir ornek sozluk olsun.
print(pd.Series(notlar)) #diyerek siraya gore karsilikli row column iliskili yazdirabiliyoruz

ali        75
mustafa    85
aybuke     80
dtype: int64


#####  tabi bu islemleri diziler ve arraylar ile de yapabiliriz<br> burda kullanim soyledir: __Series(data,index)__ mantigidir. Ilk basa **data'lar** sonra **index'ler** yazilir.

In [3]:
isim = ["ali","mustafa","aybuke"]
sonuclar=[75,85,80]
print(pd.Series(isim),"\n\n") #dersek "isim" dekileri index mantigina göre row-column seklinde yazacaktir
print(pd.Series(isim,sonuclar)) #tabi bunu pd.Series(data=isim, index=sonuclar) seklinde de yazabiliriz

0        ali
1    mustafa
2     aybuke
dtype: object 


75        ali
85    mustafa
80     aybuke
dtype: object


### NumPY ile peki

In [4]:
arr1 = np.array([5,10,15,20]) #diyerek  tek boyutlu bir array olsun.
print(pd.Series(arr1)) #seklinde de kullanabiliyoruz

0     5
1    10
2    15
3    20
dtype: int64


### Arithmetic ile peki

##### toplama islemi yapabiliriz. burda eslesme olursa eger toplayip verecektir. Yok eger bulunamazsa **NAN** verecektir. Ama sonuc olarak hata vermicek. Hemen incelemeye gecelim

In [5]:
sinav1 = pd.Series(data=[60,65,70], index=["cahide","timur","ersever"])
sinav2 = pd.Series(data=[30,45,20], index=["cahide","timur","ersever"])
print(sinav1["ersever"],"\n") #diyip 'ersever'in sonucunu isteyebiliyoruz

total=sinav1+sinav2 #diyip bu ikisini toplayabiliyoruz isim deger eslesmesi yaparak
print(total)

70 

cahide      90
timur      110
ersever     90
dtype: int64


#### peki index degerleri farkli olsaydi?

In [6]:
example1=pd.Series([1,2,3,4],["a","b","c","d"])
example2=pd.Series([5,6,7,8],["a","c","f","g"]) #olsuun
print(example1+example2)


a    6.0
b    NaN
c    9.0
d    NaN
f    NaN
g    NaN
dtype: float64


#### sonucu incelersek;<br>1-'a' icin herhangi bir problem yok<br>2-'b' example1'de var fakat example2'de olmadigi icin Nan aliyor.<br>3-'c' example1'de 2. index, example2'de 1. index fakat her ikisinde de bulundugu icin yeri fark etmeksizin toplanmis.<br>4-'d', 'f' ve 'g' ise 'b' ile ayni durum yasiyor<br><br> __NaN__ 'i bulamadigi degerler icin verir

##### aklimiza sey gelebilir: ayni indexler olmasada birlestirsin, varsa toplasin yoksa da kaybetmesin istiyoruz, bazen kaybetsin bazen kaybetmesin istiyoruz ' olabiliriz . gorecegizzz

# Data Frames

#### iki boyutlu, etiketli bir veri yapısıdır. Tıpkı bir Excel tablosu veya SQL veritabanı tablosu gibi düşünebilirsin.

In [7]:
veri=np.random.randn(4,3) #seklinde olusturalim
print(veri)
#bu bir Datafreme dir. Series ile calismak istersek hata aliriz

[[-0.21346703 -1.44198538 -0.09717341]
 [-0.013139    0.95129473 -0.53285696]
 [ 1.75838107 -0.12501681  0.86019206]
 [-1.25712455 -0.64192621 -1.24141849]]


In [8]:
#data_frame=pd.Series(veri) bu bize hata verecektir.
data_frame=pd.DataFrame(veri)
print(data_frame)
print(type(data_frame),"\n") #bu tipini dataFrame olarak verir
print(data_frame[0],"\n") #bu bize 0 column'unu verir
print(type(data_frame[0]),"\n") #bu ise tipini series olarak vercektir. cunku sectigimiz yer tek boyutlu.

          0         1         2
0 -0.213467 -1.441985 -0.097173
1 -0.013139  0.951295 -0.532857
2  1.758381 -0.125017  0.860192
3 -1.257125 -0.641926 -1.241418
<class 'pandas.core.frame.DataFrame'> 

0   -0.213467
1   -0.013139
2    1.758381
3   -1.257125
Name: 0, dtype: float64 

<class 'pandas.core.series.Series'> 



##### indexlere ve column'lara isim verelim cunku boyle guzel durmuyor;

In [22]:
new_data_frame=pd.DataFrame(veri,index=["ali","aybuke","catli","pala"], columns=["not","maas","boy"]) #index->row ismi icin, columns->column ismi icin;
print(new_data_frame)

             not      maas       boy
ali    -0.213467 -1.441985 -0.097173
aybuke -0.013139  0.951295 -0.532857
catli   1.758381 -0.125017  0.860192
pala   -1.257125 -0.641926 -1.241418


In [23]:
print(new_data_frame["not"],"\n")#diyerek 'not' columnunu alabiliriz
print(new_data_frame[["not","maas"]],"\n") #seklinde list icinde list kullanarak istedigimiz kadar column'u cagirabiliriz

ali      -0.213467
aybuke   -0.013139
catli     1.758381
pala     -1.257125
Name: not, dtype: float64 

             not      maas
ali    -0.213467 -1.441985
aybuke -0.013139  0.951295
catli   1.758381 -0.125017
pala   -1.257125 -0.641926 



##### new_data_frame["x"] seklinde **column** cagirabiliriz. peki row? __-new_data_frame.loc["x"]__ diyerek row cagirabiliriz

In [24]:
print(new_data_frame.loc["ali"],"\n") #goruldugu uzere 'ali'e ait bilgileri getirir
print(new_data_frame.iloc[0],"\n") #yani column locationu index degeri ne ise bu sekilde de cagirabiliriz. 
print(new_data_frame.iloc[1],"\n") 

not    -0.213467
maas   -1.441985
boy    -0.097173
Name: ali, dtype: float64 

not    -0.213467
maas   -1.441985
boy    -0.097173
Name: ali, dtype: float64 

not    -0.013139
maas    0.951295
boy    -0.532857
Name: aybuke, dtype: float64 



##### __iloc[:,x]__ kullanimi:<br>1-':' butun row'ari sec demek<br>2-hangi index'deki column almak istersek yazabiliriz 

In [25]:
print(new_data_frame.iloc[:,0])#mesela ornek kullanimi


ali      -0.213467
aybuke   -0.013139
catli     1.758381
pala     -1.257125
Name: not, dtype: float64


## Data Manipulasyonu

##### simdi normalde __new_data_frame["not"]__ yapip 'name' column'unu cagirabilirim.<br> Ama new_data_frame["plus"] dersem nolcak. Normalde 'plus' column'u olmadigi icin bunu eklicek __column__ olarak<br> Hatta buna herkese esit gelcek sekilde deger de verebiliriz--> __new_data_frame["plus"]=8__ mesela

In [26]:
new_data_frame["not"]

ali      -0.213467
aybuke   -0.013139
catli     1.758381
pala     -1.257125
Name: not, dtype: float64

In [27]:
new_data_frame["extra"]=8
print(new_data_frame)

             not      maas       boy  extra
ali    -0.213467 -1.441985 -0.097173      8
aybuke -0.013139  0.951295 -0.532857      8
catli   1.758381 -0.125017  0.860192      8
pala   -1.257125 -0.641926 -1.241418      8


##### simdi belli bir column'u silmek icin __new_data_frame.drop("extra",axis=1,  )__ deriz. Nedir bu axis?<br>Normal bir sekilde aslinda **row icin axis=0, column icin axis=1**'dir. Yani matematikde eksen mantigi gibi.<br><br>bu __.drop()__ fonksiyonunu cagirirken default olarak __axis=0__ dir. Yani diyelim ki ayni ada sahip hem row hem de column var. Eger sen __axis'i__ belirtmeden cagirirsan foknsiyonu default degerinden dolayi __row'dakini__ silecektir 

In [28]:
new_data_frame=new_data_frame.drop("extra", axis=1) #diyebilir ya da 
#new_data_frame.dro("extra", axis=1, inplace=True) -->bunu icerisinde yaptirmasini saglar.
print(new_data_frame) #goruldugu uzere 'extra' column'u gitti

             not      maas       boy
ali    -0.213467 -1.441985 -0.097173
aybuke -0.013139  0.951295 -0.532857
catli   1.758381 -0.125017  0.860192
pala   -1.257125 -0.641926 -1.241418


##### peki ben __row_column__ eslesmesi yaparak yani diyelim ki __ali'nin notu'nu görmek istiyorsam__ nne yapacagim demi..

In [34]:
print(new_data_frame.loc["ali"]["not"],"\n") # ya da sey diyebilirim;
print(new_data_frame.loc["aybuke","not"])

#yani ya yan yana koseli ayri parantezlerle ya da ayni koseli parantez icinde ',' ile ayrilmis sekilde

-0.21346702597962033 

-0.01313899834337245


##### peki bu sekilde degerini degistirebilir miyiz? Tabi ki :)

In [37]:
new_data_frame.loc["aybuke","maas"]=50
print(new_data_frame.loc["aybuke","maas"])
print(new_data_frame)

50.0
             not       maas       boy
ali    -0.213467  -1.441985 -0.097173
aybuke -0.013139  50.000000 -0.532857
catli   1.758381  -0.125017  0.860192
pala   -1.257125  -0.641926 -1.241418


#### filtreleme islemleri de yapilabilir

In [40]:
print(new_data_frame>0)
print(new_data_frame[new_data_frame>0])
print(new_data_frame[new_data_frame["not"]<0])

          not   maas    boy
ali     False  False  False
aybuke  False   True  False
catli    True  False   True
pala    False  False  False
             not  maas       boy
ali          NaN   NaN       NaN
aybuke       NaN  50.0       NaN
catli   1.758381   NaN  0.860192
pala         NaN   NaN       NaN
             not       maas       boy
ali    -0.213467  -1.441985 -0.097173
aybuke -0.013139  50.000000 -0.532857
pala   -1.257125  -0.641926 -1.241418


## Index Mantigi

##### bazen index'ler icin 0,1,2,3... gibi gitmesi bizim icin daha mantikli olabilir.<br> __new_data_frame.reset_index()__ dersek 0,1,2,3 diye atayacaktir index'i ve bizim isimlerden olusan index'ler icin __'index' adinda column__ acacaktir

In [42]:
print(new_data_frame.reset_index())#goruldugu uzere boyle bisi olr

    index       not       maas       boy
0     ali -0.213467  -1.441985 -0.097173
1  aybuke -0.013139  50.000000 -0.532857
2   catli  1.758381  -0.125017  0.860192
3    pala -1.257125  -0.641926 -1.241418


In [45]:
reset_df=new_data_frame.reset_index() #diyelim
#print(reset_df.loc["ali"]) dersek bize hata verecektir cunku artık index mantigina göre buraya 0 yazmaliyiz
print(reset_df.loc[0]) #diyerek cagirabiliriz artik cunku index degisti!

index         ali
not     -0.213467
maas    -1.441985
boy     -0.097173
Name: 0, dtype: object


##### biz index'i degistirmek isteye de biliriz

In [53]:
yeni_indexler=["ila","ekubya","iltac","alap"]
new_data_frame["yeniIndex"]=yeni_indexler #diyip yeni column eklerim ve icerisine bu degerleri koyarim
print(new_data_frame)

                not       maas       boy yeniIndex
yeniIndex                                         
ila       -0.213467  -1.441985 -0.097173       ila
ekubya    -0.013139  50.000000 -0.532857    ekubya
iltac      1.758381  -0.125017  0.860192     iltac
alap      -1.257125  -0.641926 -1.241418      alap


In [54]:
new_data_frame.set_index("yeniIndex", inplace=True) #deyip yapabilirim
print(new_data_frame,"\n")
print(new_data_frame.loc["ila"])

                not       maas       boy
yeniIndex                               
ila       -0.213467  -1.441985 -0.097173
ekubya    -0.013139  50.000000 -0.532857
iltac      1.758381  -0.125017  0.860192
alap      -1.257125  -0.641926 -1.241418 

not    -0.213467
maas   -1.441985
boy    -0.097173
Name: ila, dtype: float64


## Multi Index

In [59]:
index1=["atal","atal","atal","aybu","aybu","aybu"]
index2=["ali","ahmet","habibe","mustafa","fatih","sabit"]
ziplenmis=list(zip(index1,index2))


###### biz bunlardan data_frame olusturmak istiyoruz. Tabi Multi index yani gruplanmis index seklinde istiyoruz

In [60]:
print(ziplenmis)

[('atal', 'ali'), ('atal', 'ahmet'), ('atal', 'habibe'), ('aybu', 'mustafa'), ('aybu', 'fatih'), ('aybu', 'sabit')]


In [62]:
ziplenmis=pd.MultiIndex.from_tuples(ziplenmis) #diyerek multi index haline getirelim
ornek_degerler=np.zeros((6,2)) #bu boyut belirlerken ziplenmis'in boyutuna gore uycak sekilde vermelisin

In [64]:
big_data_frame=pd.DataFrame(ornek_degerler, index=ziplenmis, columns=["yas","salary"])
print(big_data_frame)

              yas  salary
atal ali      0.0     0.0
     ahmet    0.0     0.0
     habibe   0.0     0.0
aybu mustafa  0.0     0.0
     fatih    0.0     0.0
     sabit    0.0     0.0


##### burda __print(big_data_frame.loc["ali"])__ diyemeyiz!!! cunku o __index'in index'i__. <br> sey diyebiliriz __print(big_data_frame.loc["atal"])__ <br> 'ali' yi cagirmak istersek eger, __print(big_data_frame.loc["ali"].loc["ali"])__ diyebilirim

In [65]:
print(big_data_frame.loc["atal"],"\n")
print(big_data_frame.loc["atal"].loc["ali"])

        yas  salary
ali     0.0     0.0
ahmet   0.0     0.0
habibe  0.0     0.0 

yas       0.0
salary    0.0
Name: ali, dtype: float64
