In [18]:
import numpy as np #diyerek 'import' etmemiz yani cagirmamiz gerekiyor. eger yuklu degilse"!pip install numpy"


In [19]:
list1=[1,2,3,4,5] #normal bir list
np_array_list = np.array(list1) #diyerek list1'in array tipini np_array_list' e esitlemis olduk

print(type(np_array_list))# dersek bize numpy.ndarray ciktisini vercektir

# np_array_list. dersek karsimiza arrat icin kullanabilecegimiz cok fazla fonk cikacaktir. Normal bir diziye gore cok fazla
print(np_array_list.max()) # dersek bize max elemani verecektir

print(np.ones(5)) # dersek bize 5 elemanli elemanlarin hepsi 1 olan bir array oluşturacaktir. np.zeros-->0'lardan. ..np.random.random-->0-1 arasi random sayi



<class 'numpy.ndarray'>
5
[1. 1. 1. 1. 1.]


## Array Arithmetic


##### l1=[1,2], l2=[3,4] diye iki liste var. eger l1+l2 yaparsak sonuc: [1,2,3,4] seklinde olacaktir yani yan yana koyar.Ama arrayda durum farklidir.

In [20]:
l1=[1,2]
l2=[3,4]
array1=np.array(l1)
array2=np.array(l2)#olsun


##### array1 + array2 yapilirsa sonuc: [4,6] olacak. indextekileri birbiriyle toplayacaktir. Sadece + degil -,*,/ islemeleri de yapabiliriz
##### <bw>Fakat bu islemleri yaparken birinin index sayisi farkli olursa bize __"operands couldn't be broadcast together with shapes"__ hatasi verecektir.

## Indexing & Arange

##### normalde list'lerde list(range(1,5)) dersek bize [1,2,3,4] seklinde bir list verecek. <bw> Ayni mantik array icin de var. 

In [21]:
print(np.arange(0,5))# dersek bize [0,1,2,3,4] seklinde array olusturacaktir. 
print(np.arange(1,10,3))


#tabi ki index mantiği da vardir.
arr1=np.arange(1,10)
print(arr1[0]) #denilince ilk indexi verecektir.
print(arr1[-1]) #tahmin edileceği gibi son indexteki elemani verecektir
print(arr1[1:4], arr1[::-1]) #slicing islemleri de calisiyor goruldugu uzere


[0 1 2 3 4]
[1 4 7]
1
9
[2 3 4] [9 8 7 6 5 4 3 2 1]


##### random olaylari da tabi ki vardir

In [22]:
new_arr=np.random.randn(4) #bu olay bize 4 elemanli random sayilardan olusan bir array olusturacaktır
print(new_arr,"\n")

new_arr2=np.random.randn(5,5) #bu ise 5'e 5'lik random sayilardan olusan matrix vercek.
print(new_arr2,"\n")

new_arr3=np.random.randint(1,25,4) #bu da 1-25 arasi 4 tane random int'den olusan array verecektir.
print(new_arr3,"\n")

[ 0.64208508  1.9525044  -1.14229955 -0.2847442 ] 

[[-0.5264895   1.3476072  -0.03353316  1.01527739  1.10210519]
 [-0.70570515 -0.84053792  1.46641607 -1.02040687  0.04957674]
 [-1.4773675   0.27759996 -0.05874849 -0.49561823  1.54818095]
 [ 0.39645949 -0.81479007 -2.40412891  0.21892717  1.17373471]
 [-0.65597846  0.40543228  0.59718529  0.67796683 -0.93075036]] 

[10  5 23  2] 

