In [2]:
import numpy as np

##### aslinda biz list kullanarak da matrix yapabiliyoruz. liste1=[[1,2,3],[4,5,6]] diye 2 satir 3 sutunu olan bir matrix<br> Burda onemli olan __row*column__. Her matrix'te matrix'i incelerken bu siraya gore bakilmali.

In [3]:
np_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])# diyerek 3 row 3 column'u olan bir matirx olusturduk
print(np_matrix,"\n")

print(np_matrix[1][1],"\n") #diyerek normal index mantiğinin oldugunu gormus oluruz

print(np_matrix.sum(),"\n") #burda da butun elemanlarini toplariz. Bu ve bunun gibi bircok ozellik de barindirir icerisinde

#row*column ozeeligine her yerde dikkat ve onem vermeliyiz
print(np.ones((3,4)),"\n") #diyerek 3 row 4 column'lu 1'lerden olusan matrix yapabiliriz.
print(np.random.random((2,4))) #goruldugu gibi bu ve bunun gibi ozellikler de mevcuttur.

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

5 

45 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[0.28806905 0.34677658 0.0659452  0.25199965]
 [0.69928138 0.05903584 0.67602032 0.08230771]]


## Matrix Arithmetic

In [4]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])#diyerek iki tane (2,2) matrix olusturalim
print(arr1+arr2,"\n") #bunlari tabiki toplayabiliriz

[[ 60  80]
 [100 120]] 



##### toplama ve cikarma islemlerinde matrix'ler arasinda __shape__ uyumlulugu olmasi gerekiyor.

In [5]:
arr3=np.array([[90,100]]) #seklinde (1,2)'lik bir matrix olsun.
print(arr3+arr1,"\n") #denersek [90,100]'u indexlere karsilikli gelcek sekilde butun satirlara toplicaktir

[[100 120]
 [120 140]] 



##### Fakat arr4=[[1,2,3,4]] gibi bisi olsa ve __arr1+arr4__ dersek tabi ki de olmayacaktir.

In [6]:
arr4=np.array([[110],[120]]) #seklinde (2,1) lik bir matrix olsun
print(arr4+arr1,"\n") #dersek bunu da column mantiginda toplicaktir.(aklindan resmini hayal edebilirsin:>)

[[120 130]
 [150 160]] 



## Matrix Multipication


##### simdi normalde biz iki tane array'i birbiriyle carpabiliriz ama bu normal index'e gore yani beklenen carpimdir.<br> Fakat is matrix carpimina gelince degisir.<br> Matrix'lerde __dot produc__ vardır.

##### iki tane matrix'e __dot porduct__ islemini uygulamak icin belli basli sartlar vardır<br>1-ilk matris'in __column sayisi__ ile ikinci matrix'in __row__ sayisi birbirine esit olmalidir.<br> 2-Sonucun row degeri ise ilk matrix'in row sayisi, column degeri ise ikinci matrix'in column sayisidir.<br><br><br>Yani ornek olarak ilk_matris:(x,y) lik olsun. ikinci_matris:(y,z) olsun. sonuc:(x,z) olur.<br>Peki bunlar nasıl carpilir?<br>Elimizde ar1=[[10,20],[30,40],[50,60]]-->(3,2) ve ar2=[[2,3,4,5],[1,2,3,4]]-->(2,4) matrixlerimiz olsun<br>sonucumuz (3,4) seklinde olacak.<br> ilk olarak ar1[0][0] ile ar2[0][0] ve ar1[0][1] ile ar2[1][0] carpilir ve toplanir-->10*2 + 20*1 =40 bu deger sonuc[0][0] ' esittir. <br> sonra ise ayni ar1[0][0] ile ar2[0][1] ve ar1[0][1] ile ar2[1][1] carpilir ve toplanir-->10*3 + 20*2=70 bu deger sonuc[0][1]'dir.<br>aynı ar1[0] daki elemanlari devam edecek sekilde carparak sonuc[0]'i olusturuyoruz. ar1[1]'de de benzer islemleri yaparak sonuc[1] i olustururuz. carpim bu mantiktadir

In [8]:
ar1=np.array([[10,20],[30,40],[50,60]])
ar2=np.array([[2,3,4,5],[1,2,3,4]])
sonuc=ar1.dot(ar2)#bu fonksiyonu kullanarak numpy'da kolayca carpabiliyoruz
print(sonuc)

[[ 40  70 100 130]
 [100 170 240 310]
 [160 270 380 490]]
